# dorsyadan veri okuma işlemleri
dosya = open("deneme.txt","rt")
# print(dosya.read(10))
# #print(type(dosya.read()))
# # print(dosya.read())
# icerik = dosya.read()
# print(icerik)
icerik = dosya.read()
print(icerik)
icerik2 = dosya.read()
print(icerik2)