# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesapmak.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.alan1 = QtWidgets.QLineEdit(Form)
        self.alan1.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.alan1.setObjectName("alan1")
        self.alan2 = QtWidgets.QLineEdit(Form)
        self.alan2.setGeometry(QtCore.QRect(150, 40, 113, 20))
        self.alan2.setObjectName("alan2")
        self.lbl_sonuc = QtWidgets.QLabel(Form)
        self.lbl_sonuc.setGeometry(QtCore.QRect(320, 40, 47, 13))
        self.lbl_sonuc.setObjectName("lbl_sonuc")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        self.btn_topla = QtWidgets.QPushButton(Form)
        self.btn_topla.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.btn_topla.setObjectName("btn_topla")
        self.btn_cikar = QtWidgets.QPushButton(Form)
        self.btn_cikar.setGeometry(QtCore.QRect(110, 100, 75, 23))
        self.btn_cikar.setObjectName("btn_cikar")
        self.btn_carp = QtWidgets.QPushButton(Form)
        self.btn_carp.setGeometry(QtCore.QRect(190, 100, 75, 23))
        self.btn_carp.setObjectName("btn_carp")
        self.btn_bol = QtWidgets.QPushButton(Form)
        self.btn_bol.setGeometry(QtCore.QRect(280, 100, 75, 23))
        self.btn_bol.setObjectName("btn_bol")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_sonuc.setText(_translate("Form", "Sonuç"))
        self.label_2.setText(_translate("Form", "Sayi 1"))
        self.label_3.setText(_translate("Form", "Sayi 2"))
        self.btn_topla.setText(_translate("Form", "+"))
        self.btn_cikar.setText(_translate("Form", "-"))
        self.btn_carp.setText(_translate("Form", "*"))
        self.btn_bol.setText(_translate("Form", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
