# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesapmak.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import *
import sys
from hesapmakui import Ui_Form

class HesapMakinesi(QWidget, Ui_Form):
    def __init__(self):
        super(HesapMakinesi, self).__init__()
        self.setupUi(self)

        self.btn_bol.clicked.connect(self.bol)
        self.btn_topla.clicked.connect(self.topla)
        self.btn_cikar.clicked.connect(self.cikar)
        self.btn_carp.clicked.connect(self.carp)

    def topla(self):
        toplam = int(self.alan1.text()) + int(self.alan2.text())
        self.lbl_sonuc.setText(str(toplam))

    def cikar(self):
        cikar = int(self.alan1.text()) - int(self.alan2.text())
        self.lbl_sonuc.setText(str(cikar))
    def bol(self):
        bolum = int(self.alan1.text()) / int(self.alan2.text())
        self.lbl_sonuc.setText(str(bolum))
    def carp(self):
        if self.kontrol() is not False:
            carpim = int(self.alan1.text()) * int(self.alan2.text())
            self.lbl_sonuc.setText(str(carpim))

    def kontrol(self):
        if self.alan1.text() == "" or "" == self.alan2.text():
            self.lbl_sonuc.setText("Boş Alan Bırakmayın")
            return False
        else:
            return (int(self.alan1.text()),int(self.alan2.text()))

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)

    ui = HesapMakinesi()

    ui.show()
    sys.exit(app.exec_())
