# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kitapTablosu = QtWidgets.QTableWidget(self.centralwidget)
        self.kitapTablosu.setGeometry(QtCore.QRect(10, 10, 771, 561))
        self.kitapTablosu.setObjectName("kitapTablosu")
        self.kitapTablosu.setColumnCount(5)
        self.kitapTablosu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.kitapTablosu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.kitapTablosu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.kitapTablosu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.kitapTablosu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.kitapTablosu.setHorizontalHeaderItem(4, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuKitaplik = QtWidgets.QMenu(self.menubar)
        self.menuKitaplik.setObjectName("menuKitaplik")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionKitaplarim = QtWidgets.QAction(MainWindow)
        self.actionKitaplarim.setObjectName("actionKitaplarim")
        self.actionKitap_Ekle = QtWidgets.QAction(MainWindow)
        self.actionKitap_Ekle.setObjectName("actionKitap_Ekle")
        self.menuKitaplik.addAction(self.actionKitaplarim)
        self.menuKitaplik.addAction(self.actionKitap_Ekle)
        self.menubar.addAction(self.menuKitaplik.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.kitapTablosu.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Kitap Id"))
        item = self.kitapTablosu.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kitap Adi"))
        item = self.kitapTablosu.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Kitap Sayfa Sayısı"))
        item = self.kitapTablosu.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Guncelle"))
        item = self.kitapTablosu.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sil"))
        self.menuKitaplik.setTitle(_translate("MainWindow", "Kitaplik"))
        self.actionKitaplarim.setText(_translate("MainWindow", "Kitaplarim"))
        self.actionKitap_Ekle.setText(_translate("MainWindow", "Kitap Ekle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
