# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
import sys
from anaekranui import Ui_MainWindow
class AnaEkran(QMainWindow, Ui_MainWindow):
   def __init__(self):
       super(AnaEkran, self).__init__()
       self.setupUi(self)
if __name__ == "__main__":
    app = QApplication(sys.argv)
    anaekran = AnaEkran()
    anaekran.show()
    sys.exit(app.exec_())
