# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Giris_Formu(object):
    def setupUi(self, Giris_Formu):
        Giris_Formu.setObjectName("Giris_Formu")
        Giris_Formu.resize(400, 300)
        self.label = QtWidgets.QLabel(Giris_Formu)
        self.label.setGeometry(QtCore.QRect(77, 9, 224, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.girisButonu = QtWidgets.QPushButton(Giris_Formu)
        self.girisButonu.setGeometry(QtCore.QRect(77, 268, 75, 23))
        self.girisButonu.setObjectName("girisButonu")
        self.kAdiEdit = QtWidgets.QLineEdit(Giris_Formu)
        self.kAdiEdit.setGeometry(QtCore.QRect(77, 216, 133, 20))
        self.kAdiEdit.setObjectName("kAdiEdit")
        self.kSifreEdit = QtWidgets.QLineEdit(Giris_Formu)
        self.kSifreEdit.setGeometry(QtCore.QRect(77, 242, 133, 20))
        self.kSifreEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.kSifreEdit.setObjectName("kSifreEdit")
        self.label_2 = QtWidgets.QLabel(Giris_Formu)
        self.label_2.setGeometry(QtCore.QRect(9, 216, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Giris_Formu)
        self.label_3.setGeometry(QtCore.QRect(9, 242, 62, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Giris_Formu)
        QtCore.QMetaObject.connectSlotsByName(Giris_Formu)

    def retranslateUi(self, Giris_Formu):
        _translate = QtCore.QCoreApplication.translate
        Giris_Formu.setWindowTitle(_translate("Giris_Formu", "Form"))
        self.label.setText(_translate("Giris_Formu", "Kitaplık Programına Hoşgeldiniz"))
        self.girisButonu.setText(_translate("Giris_Formu", "Giriş"))
        self.label_2.setText(_translate("Giris_Formu", "Kullanıcı Adı"))
        self.label_3.setText(_translate("Giris_Formu", "Kullanıcı Şifre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Giris_Formu = QtWidgets.QWidget()
    ui = Ui_Giris_Formu()
    ui.setupUi(Giris_Formu)
    Giris_Formu.show()
    sys.exit(app.exec_())
