# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kitap_ekleme.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kitapKaydetmeFormu(object):
    def setupUi(self, kitapKaydetmeFormu):
        kitapKaydetmeFormu.setObjectName("kitapKaydetmeFormu")
        kitapKaydetmeFormu.resize(400, 300)
        self.formLayoutWidget = QtWidgets.QWidget(kitapKaydetmeFormu)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 50, 301, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.kitapAdLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.kitapAdLabel.setObjectName("kitapAdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kitapAdLabel)
        self.kitapAdiEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.kitapAdiEdit.setObjectName("kitapAdiEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kitapAdiEdit)
        self.sayfaSaySLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.sayfaSaySLabel.setObjectName("sayfaSaySLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sayfaSaySLabel)
        self.sayfaSayisiEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sayfaSayisiEdit.setObjectName("sayfaSayisiEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sayfaSayisiEdit)
        self.btn_kitap_ekle = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_kitap_ekle.setObjectName("btn_kitap_ekle")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_kitap_ekle)

        self.retranslateUi(kitapKaydetmeFormu)
        QtCore.QMetaObject.connectSlotsByName(kitapKaydetmeFormu)

    def retranslateUi(self, kitapKaydetmeFormu):
        _translate = QtCore.QCoreApplication.translate
        kitapKaydetmeFormu.setWindowTitle(_translate("kitapKaydetmeFormu", "Kitap Kayıt Formu"))
        self.kitapAdLabel.setText(_translate("kitapKaydetmeFormu", "Kitap Adı"))
        self.sayfaSaySLabel.setText(_translate("kitapKaydetmeFormu", "Sayfa Sayısı"))
        self.btn_kitap_ekle.setText(_translate("kitapKaydetmeFormu", "Kitap Kaydet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kitapKaydetmeFormu = QtWidgets.QWidget()
    ui = Ui_kitapKaydetmeFormu()
    ui.setupUi(kitapKaydetmeFormu)
    kitapKaydetmeFormu.show()
    sys.exit(app.exec_())
